const product = [
  {
    id: 1,
    imgUrl: "ac.png",
    category: "Home Appliances",
    price: "30,000",
    rating: "4.7",
    ratingCount: "2904",
    title: "Blue Star Invetor AC",
  },
  {
    id: 2,
    imgUrl: "https://shop.globalbees.com/cdn/shop/products/51NT-2owTcL.jpg?v=1689081769",
    category: "Travel",
    price: "1,876",
    rating: "4.4",
    ratingCount: "10,987",
    title: "Wisdom Travel Bag",
  },
  {
    id: 3,
    imgUrl: "headset.png",
    category: "Electronics",
    price: "870",
    rating: "4.9",
    ratingCount: "1,90,876",
    title: "Zebronics Wireless Headset",
  },
  {
    id: 4,
    imgUrl: "keyboard.png",
    category: "Electronics",
    price: "450",
    rating: "4.2",
    ratingCount: "105",
    title: "Dell wired Keyboard",
  },
  {
    id: 5,
    imgUrl: "https://images.jdmagicbox.com/quickquotes/images_main/asus-laptops-22-02-2022-054-270824236-s95u6p0h.png",
    category: "Electronnics",
    price: "86,990",
    rating: "4.2",
    ratingCount: "3680",
    title: "ASUS Gaming Laptop",
  },
  {
    id: 6,
    imgUrl: "https://t3.ftcdn.net/jpg/06/25/07/28/360_F_625072874_eRoy4HUb8IOzTxCnS6jLT32ChaPG3rvb.jpg",
    category: "Electronics",
    price: "380",
    rating: "3.8",
    ratingCount: "870",
    title: "LogiTech Wired Mouse",
  },
  {
    id: 7,
    imgUrl: "https://inventstore.in/wp-content/uploads/2023/04/Blue-scaled.webp",
    category: "Electronics",
    price: "85,999",
    rating: "4.1",
    ratingCount: "2467",
    title: "IPhone 16 Pro Max",
  },
  {
    id: 8,
    imgUrl: "redmi.png",
    category: "Electroics",
    price: "30,999",
    rating: "4.6",
    ratingCount: "10,864",
    title: "Redmi 13 5G",
  },
  {
    id: 9,
    imgUrl: "nike.png",
    category: "Travel",
    price: "2,875",
    rating: "3.9",
    ratingCount: "8,268",
    title: "Nike Sports Shoe",
  },
  {
    id: 10,
    imgUrl: "https://img.freepik.com/free-photo/tv-screen-wooden-table-front-lake-with-sunset_1142-56610.jpg",
    category: "Home Appliances",
    price: "50,879",
    rating: "4.5",
    ratingCount: "1875",
    title: "Redmi 4K LED TV",
  },
];
export default product;